In [1]:
import pandas as pd

### Read Data and Check Data

In [2]:
df = pd.read_csv(r'D:\PythonProject\retail-sales-prediction\data\raw\retail_sales_dataset.csv')
df

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [3]:
print('Df shape:', df.shape)
df.info()

Df shape: (1000, 9)
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [4]:
df.isnull().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [5]:
df.isna().sum()

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.columns = (
df.columns
.str.lower()
.str.strip()
.str.replace(" ", "_")
)

df.columns.to_list()

['transaction_id',
 'date',
 'customer_id',
 'gender',
 'age',
 'product_category',
 'quantity',
 'price_per_unit',
 'total_amount']

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    1000 non-null   int64
 1   date              1000 non-null   str
 2   customer_id       1000 non-null   str
 3   gender            1000 non-null   str
 4   age               1000 non-null   int64
 5   product_category  1000 non-null   str
 6   quantity          1000 non-null   int64
 7   price_per_unit    1000 non-null   int64
 8   total_amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

In [32]:
# convert date to datetime
df['date'] = pd.to_datetime(df['date'])

I notice customer_id and transaction_id have similiar values, so I decied to check

In [33]:
# check nunique value and is there customer has 2 transaction_id?
print("cust_id:",df['customer_id'].nunique())
print("transaction_id:",df['transaction_id'].nunique())
print("sum of transaction_id > 1:",(df.groupby('customer_id')['transaction_id'].value_counts() > 1).sum())

cust_id: 1000
transaction_id: 1000
sum of transaction_id > 1: 0

### Dropped Features

- transaction_id was remove because it a unique identifier and does not contain predictive information.
- customer_id was remove because every customer appears only once in the dataset, making it an identifier rather than a useful feature

In [ ]:
df = df.drop(columns=['transaction_id', 'customer_id'])
df

### Check Outlier

In [ ]:
# check quantity have minus value or not
df[df['quantity'] < 0]

Empty DataFrame
Columns: [transaction_id, date, customer_id, gender, age, product_category, quantity, price_per_unit, total_amount]
Index: []

In [ ]:
# check price_per_unit have 0 value or not
df[df['price_per_unit'] == 0]

Empty DataFrame
Columns: [transaction_id, date, customer_id, gender, age, product_category, quantity, price_per_unit, total_amount]
Index: []

### Save Clean Dataset

In [38]:
df.to_csv(r"..\data\processed\retail_sales_cleaned.csv", index=False)